//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Ruta { get; set; }
        public string Usu { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> TC { get; set; }
        public string EcepCC { get; set; }
        public string IRFS { get; set; }
        public string Activo { get; set; }
        public Nullable<int> Rut { get; set; }
        public string BLK { get; set; }
        public Nullable<int> TCFac { get; set; }
        public Nullable<double> Tarifa { get; set; }
        public Nullable<int> TCFac1 { get; set; }
        public Nullable<double> Tarifa1 { get; set; }
        public string CC { get; set; }
        public string Holding { get; set; }
        public Nullable<int> BA { get; set; }
        public Nullable<int> ER { get; set; }
        public Nullable<int> SegMon { get; set; }
        public string BLKPag { get; set; }
        public string TES { get; set; }
        public Nullable<int> BcoPag { get; set; }
        public string CtaPag { get; set; }
        public string EmailPag { get; set; }
        public Nullable<int> MPago { get; set; }
        public string Obs { get; set; }
        public string Consi { get; set; }
        public string AdmCheque { get; set; }
        public string RRHH { get; set; }
        public Nullable<int> Grati { get; set; }
        public string ObsGrati { get; set; }
        public Nullable<int> Cola { get; set; }
        public string ObsCola { get; set; }
        public Nullable<int> Mov { get; set; }
        public string ObsMov { get; set; }
        public Nullable<int> Fpago { get; set; }
        public Nullable<int> Caja { get; set; }
        public string ObsCaja { get; set; }
        public Nullable<int> Mutual { get; set; }
        public string ObsMutual { get; set; }
        public Nullable<int> DiaSueldo { get; set; }
        public Nullable<int> DiaPago { get; set; }
        public Nullable<int> DiaAnticipo { get; set; }
        public string ObsRRHH { get; set; }
        public Nullable<int> PagaPSO { get; set; }
        public string emailcobro { get; set; }
        public string atencion { get; set; }
        public string TramoPR { get; set; }
        public string IIng { get; set; }
        public Nullable<int> TipChe { get; set; }
        public string rutadestino { get; set; }
        public string CTD { get; set; }
        public Nullable<System.DateTime> fechalr { get; set; }
        public Nullable<int> gbo { get; set; }
        public string impsug { get; set; }
        public Nullable<int> gerencia_bo { get; set; }
        public Nullable<int> gerencia_ss { get; set; }
        public string snr_ingl { get; set; }
        public Nullable<int> cartera_tes { get; set; }
        public Nullable<int> cartera_pay { get; set; }
        public string publicar_eeff { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fsalida { get; set; }
        public Nullable<int> cartera_oper { get; set; }
        public Nullable<int> kpif29 { get; set; }
        public string kpieeff { get; set; }
        public string nomfaccl { get; set; }
        public Nullable<bool> kpieeffhabil { get; set; }
        public Nullable<int> kpif29_automa { get; set; }
    }
}
