//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_CRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente_CRM()
        {
            this.Banco_Cliente_CRM = new HashSet<Banco_Cliente_CRM>();
            this.Contacto_Cliente_CRM = new HashSet<Contacto_Cliente_CRM>();
            this.Cuestionario_CRM = new HashSet<Cuestionario_CRM>();
            this.Direccion_CRM = new HashSet<Direccion_CRM>();
            this.Servicio_Cliente_CRM = new HashSet<Servicio_Cliente_CRM>();
        }
    
        public int ID_Cliente { get; set; }
        public Nullable<int> ID_Pais { get; set; }
        public Nullable<int> ID_Client_Service { get; set; }
        public Nullable<int> ID_Parther { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Industria { get; set; }
        public Nullable<System.DateTime> Fecha_Primer_Contacto { get; set; }
        public string Perfil { get; set; }
        public string Profile { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
        public string Referencia_Cliente { get; set; }
        public Nullable<int> ID_Cliente_Cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banco_Cliente_CRM> Banco_Cliente_CRM { get; set; }
        public virtual Usu Usu { get; set; }
        public virtual Pais_CRM Pais_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto_Cliente_CRM> Contacto_Cliente_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuestionario_CRM> Cuestionario_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion_CRM> Direccion_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio_Cliente_CRM> Servicio_Cliente_CRM { get; set; }
    }
}
