//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunas_CRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comunas_CRM()
        {
            this.Direccion_CRM = new HashSet<Direccion_CRM>();
        }
    
        public int ID_Comuna { get; set; }
        public string Nom_Comuna { get; set; }
        public int ID_Provincia { get; set; }
    
        public virtual Provincias_CRM Provincias_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion_CRM> Direccion_CRM { get; set; }
    }
}
