//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuestionario_CRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuestionario_CRM()
        {
            this.Propuesta_CRM = new HashSet<Propuesta_CRM>();
        }
    
        public int ID_Cuestionario { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public string Nombre_Cuestionario { get; set; }
        public string Cuestionario_Enviado { get; set; }
        public string Cuestionario_Recibido { get; set; }
        public Nullable<System.DateTime> Fecha_Cuestionario_Enviado { get; set; }
        public Nullable<System.DateTime> Fecha_Cuestionario_Recibido { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente_CRM Cliente_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propuesta_CRM> Propuesta_CRM { get; set; }
    }
}
