//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion_CRM
    {
        public int ID_Direccion { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Comuna { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Casa_Matriz { get; set; }
        public string Pagina_Web { get; set; }
        public string Numeracion { get; set; }
        public string Piso { get; set; }
        public string Estado { get; set; }
        public string Usu_Mod { get; set; }
        public Nullable<System.DateTime> Fecha_Mod { get; set; }
    
        public virtual Cliente_CRM Cliente_CRM { get; set; }
        public virtual Comunas_CRM Comunas_CRM { get; set; }
    }
}
