//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Cargos
    {
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> estado { get; set; }
        public string usuario_mod { get; set; }
    }
}
