//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSPSOCRMEntities : DbContext
    {
        public GSPSOCRMEntities()
            : base("name=GSPSOCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banco_Cliente_CRM> Banco_Cliente_CRM { get; set; }
        public virtual DbSet<Cliente_CRM> Cliente_CRM { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Comunas_CRM> Comunas_CRM { get; set; }
        public virtual DbSet<Contacto_Cliente_CRM> Contacto_Cliente_CRM { get; set; }
        public virtual DbSet<Contacto_CRM> Contacto_CRM { get; set; }
        public virtual DbSet<Contactos_Operacionales_CRM> Contactos_Operacionales_CRM { get; set; }
        public virtual DbSet<Cuestionario_CRM> Cuestionario_CRM { get; set; }
        public virtual DbSet<Direccion_CRM> Direccion_CRM { get; set; }
        public virtual DbSet<Documento_CRM> Documento_CRM { get; set; }
        public virtual DbSet<Pais_CRM> Pais_CRM { get; set; }
        public virtual DbSet<parametros> parametros { get; set; }
        public virtual DbSet<Parametros_CRM> Parametros_CRM { get; set; }
        public virtual DbSet<Propuesta_CRM> Propuesta_CRM { get; set; }
        public virtual DbSet<Provincias_CRM> Provincias_CRM { get; set; }
        public virtual DbSet<Region_CRM> Region_CRM { get; set; }
        public virtual DbSet<Servicio_Cliente_CRM> Servicio_Cliente_CRM { get; set; }
        public virtual DbSet<Servicio_CRM> Servicio_CRM { get; set; }
        public virtual DbSet<Tipo_Contacto_CRM> Tipo_Contacto_CRM { get; set; }
        public virtual DbSet<Usu> Usu { get; set; }
        public virtual DbSet<GS_Cargos> GS_Cargos { get; set; }
        public virtual DbSet<GS_Asig_Carg_Clie> GS_Asig_Carg_Clie { get; set; }
    }
}
