//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_CRM
    {
        public int ID_Parametro { get; set; }
        public string Grupo { get; set; }
        public string Texto { get; set; }
        public string Valor { get; set; }
    }
}
