//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propuesta_CRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propuesta_CRM()
        {
            this.Servicio_Cliente_CRM = new HashSet<Servicio_Cliente_CRM>();
        }
    
        public int ID_Propuesta { get; set; }
        public Nullable<int> ID_Cuestionario { get; set; }
        public string Fase { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<int> Horas { get; set; }
        public string Tipo_Moneda { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Fecha_Propuesta { get; set; }
        public Nullable<System.DateTime> Fecha_Aceptacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
    
        public virtual Cuestionario_CRM Cuestionario_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio_Cliente_CRM> Servicio_Cliente_CRM { get; set; }
    }
}
