//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_Cliente_CRM
    {
        public int ID_Servicio_Cliente { get; set; }
        public Nullable<int> ID_Servicio { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<int> ID_Propuesta { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string Tipo_Moneda { get; set; }
    
        public virtual Cliente_CRM Cliente_CRM { get; set; }
        public virtual Propuesta_CRM Propuesta_CRM { get; set; }
        public virtual Servicio_CRM Servicio_CRM { get; set; }
    }
}
