//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_CRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio_CRM()
        {
            this.Servicio_Cliente_CRM = new HashSet<Servicio_Cliente_CRM>();
        }
    
        public int ID_Servicio { get; set; }
        public Nullable<int> ID_Padre { get; set; }
        public string Nombre_Servicio { get; set; }
        public string Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio_Cliente_CRM> Servicio_Cliente_CRM { get; set; }
    }
}
