//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usu()
        {
            this.Cliente_CRM = new HashSet<Cliente_CRM>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Sigla { get; set; }
        public Nullable<int> Perfil { get; set; }
        public Nullable<int> Anexo { get; set; }
        public Nullable<int> IP { get; set; }
        public Nullable<int> cargo { get; set; }
        public string nomcorto { get; set; }
        public string nomususoft { get; set; }
        public string pass { get; set; }
        public Nullable<int> jefatura { get; set; }
        public string valpubeeff { get; set; }
        public Nullable<int> grupo { get; set; }
        public Nullable<int> ger { get; set; }
        public Nullable<int> gergen { get; set; }
        public Nullable<int> superv { get; set; }
        public string uactivo { get; set; }
        public Nullable<int> unidad { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_CRM> Cliente_CRM { get; set; }
        public virtual Usu Usu1 { get; set; }
        public virtual Usu Usu2 { get; set; }
    }
}
