//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class cab_anticipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cab_anticipos()
        {
            this.det_anticipos = new HashSet<det_anticipos>();
            this.files_anticipos = new HashSet<files_anticipos>();
        }
    
        public int id_anticipo { get; set; }
        public System.DateTime fec_anticipo { get; set; }
        public Nullable<int> id_tanticipo { get; set; }
        public string glosa { get; set; }
        public Nullable<System.DateTime> fec_pago { get; set; }
        public string estado { get; set; }
        public string CpbNum { get; set; }
        public int id_clie { get; set; }
        public Nullable<double> NumDoc { get; set; }
        public Nullable<int> rut_clie { get; set; }
        public string id_prov { get; set; }
        public string usu_sol { get; set; }
        public string usu_pag { get; set; }
        public System.DateTime fecha_mod { get; set; }
        public string usu_mod { get; set; }
        public Nullable<System.DateTime> fec_sol { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<det_anticipos> det_anticipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<files_anticipos> files_anticipos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
