//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctrl_acciones
    {
        public int id { get; set; }
        public string usu { get; set; }
        public Nullable<int> modulo { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> mom { get; set; }
    }
}
