//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class det_anticipos
    {
        public int id_anticipo { get; set; }
        public int id_danticipo { get; set; }
        public string cod_cta { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string TtdCod { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_mod { get; set; }
        public string usu_mod { get; set; }
    
        public virtual cab_anticipos cab_anticipos { get; set; }
    }
}
