//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docs
    {
        public int ID { get; set; }
        public string CPBMes { get; set; }
        public string CPBAño { get; set; }
        public string CodAux { get; set; }
        public string NomAux { get; set; }
        public string CTDCod { get; set; }
        public Nullable<int> NumDocI { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> Exento { get; set; }
        public Nullable<decimal> Impu { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> MovFe { get; set; }
        public Nullable<System.DateTime> MovFv { get; set; }
        public string CabGlo { get; set; }
        public string UsuEnt { get; set; }
        public Nullable<System.DateTime> Centraliza { get; set; }
        public string DSD { get; set; }
        public string Tipo { get; set; }
        public string RotuloDoc { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public string Archivo { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> Rut { get; set; }
        public string UsuImp { get; set; }
        public string Ruta { get; set; }
        public string UsuCent { get; set; }
        public string MovGlosa { get; set; }
        public string Digit { get; set; }
        public Nullable<int> NumCent { get; set; }
        public string TipoCV { get; set; }
        public Nullable<int> SP { get; set; }
        public Nullable<int> AP { get; set; }
        public Nullable<System.DateTime> PagUrg { get; set; }
        public Nullable<double> Saldo { get; set; }
        public double Expr2 { get; set; }
        public Nullable<int> IDCLIE { get; set; }
        public Nullable<System.DateTime> FechaSolPago { get; set; }
        public string UsuSolPago { get; set; }
        public string ObsPagRealizo { get; set; }
        public string ObsSolPago { get; set; }
        public string NomBan { get; set; }
        public string Cta { get; set; }
        public Nullable<int> Bco { get; set; }
        public string Email { get; set; }
        public string EmailPag { get; set; }
        public string FP { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string nom { get; set; }
        public string Obs { get; set; }
        public string Consi { get; set; }
        public Nullable<int> MontoPago { get; set; }
        public Nullable<System.DateTime> Entrega { get; set; }
        public Nullable<int> TipChe { get; set; }
        public Nullable<double> TCambio { get; set; }
        public string IRFS { get; set; }
        public string folioint { get; set; }
        public Nullable<double> NetoSM { get; set; }
        public Nullable<double> ExentoSM { get; set; }
        public Nullable<double> ImpuSM { get; set; }
        public Nullable<double> TotalSM { get; set; }
        public Nullable<System.DateTime> Imputacion { get; set; }
        public string impsug { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
        public string exkpi { get; set; }
        public string comenexpki { get; set; }
        public Nullable<System.DateTime> MovRe { get; set; }
        public Nullable<System.DateTime> flingdoc { get; set; }
        public Nullable<int> docsinimp { get; set; }
        public string ting { get; set; }
        public Nullable<System.DateTime> fofpoper { get; set; }
        public string uofpoper { get; set; }
        public string usurecep { get; set; }
        public Nullable<System.DateTime> recep { get; set; }
        public string tst { get; set; }
        public string origen { get; set; }
        public string gbof { get; set; }
        public Nullable<decimal> vdolar { get; set; }
        public string CTD { get; set; }
        public Nullable<int> id_encab { get; set; }
    }
}
