//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int id { get; set; }
        public string usuario_mod { get; set; }
        public System.DateTime fecha_mod { get; set; }
        public string estado { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usu Usu { get; set; }
    }
}
