//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Act_Prog
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public string nom { get; set; }
        public string clasif { get; set; }
        public string grupo { get; set; }
        public string area { get; set; }
        public Nullable<double> factor1 { get; set; }
        public Nullable<double> factor2 { get; set; }
    }
}
