//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_CtasCtes
    {
        public int ID { get; set; }
        public Nullable<int> Cliente { get; set; }
        public string Cta { get; set; }
        public Nullable<int> Banco { get; set; }
        public string CtaCont { get; set; }
        public Nullable<int> Moneda { get; set; }
        public string DescripCtaCont { get; set; }
        public string Obs { get; set; }
        public Nullable<bool> Principal { get; set; }
    }
}
