//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_ctrl_cump
    {
        public int id { get; set; }
        public Nullable<int> clie { get; set; }
        public Nullable<System.DateTime> periodo { get; set; }
        public Nullable<System.DateTime> mom { get; set; }
        public string usu { get; set; }
        public Nullable<int> tipo { get; set; }
        public string clasif { get; set; }
        public string nulo { get; set; }
        public Nullable<System.DateTime> compromiso { get; set; }
        public string exkpi { get; set; }
        public string tipo_carga { get; set; }
        public string comentario { get; set; }
        public Nullable<int> dias_plazo { get; set; }
    }
}
