//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Detalles
    {
        public int ID { get; set; }
        public Nullable<int> Doc { get; set; }
        public string CodCta { get; set; }
        public string CCCod { get; set; }
        public string Monto { get; set; }
        public string Aux { get; set; }
        public Nullable<int> NDOC { get; set; }
        public string TDoc { get; set; }
        public string Glosa { get; set; }
        public Nullable<double> MontoSM { get; set; }
    }
}
