//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Documentos
    {
        public int ID { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public string CPBAño { get; set; }
        public string CPBMes { get; set; }
        public string CodAux { get; set; }
        public string CTDCod { get; set; }
        public Nullable<int> NumDocI { get; set; }
        public Nullable<System.DateTime> MovFe { get; set; }
        public Nullable<System.DateTime> MovFv { get; set; }
        public string VendCod { get; set; }
        public string MovGlosa { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> Exento { get; set; }
        public Nullable<decimal> Impu { get; set; }
        public Nullable<double> Total { get; set; }
        public string NumDocF { get; set; }
        public string NomAux { get; set; }
        public string Archivo { get; set; }
        public string Usu { get; set; }
        public string CabGlo { get; set; }
        public Nullable<System.DateTime> Entrega { get; set; }
        public string UsuEnt { get; set; }
        public Nullable<System.DateTime> Centraliza { get; set; }
        public string UsuCent { get; set; }
        public Nullable<System.DateTime> Imputacion { get; set; }
        public string UsuImp { get; set; }
        public Nullable<int> NumCent { get; set; }
        public string Nula { get; set; }
        public string UsuAnu { get; set; }
        public string MotivoAnul { get; set; }
        public Nullable<int> SP { get; set; }
        public Nullable<int> AP { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
        public Nullable<System.DateTime> Scaneo { get; set; }
        public Nullable<System.DateTime> FechaSolPago { get; set; }
        public string UsuSolPago { get; set; }
        public string ObsPagRealizo { get; set; }
        public string ObsSolPago { get; set; }
        public Nullable<System.DateTime> PagUrg { get; set; }
        public string FP { get; set; }
        public string UsuRec { get; set; }
        public Nullable<System.DateTime> FecRec { get; set; }
        public Nullable<int> MontoPago { get; set; }
        public Nullable<System.DateTime> fcrea { get; set; }
        public Nullable<double> TCambio { get; set; }
        public string folioint { get; set; }
        public Nullable<double> NetoSM { get; set; }
        public Nullable<double> ExentoSM { get; set; }
        public Nullable<double> ImpuSM { get; set; }
        public Nullable<double> TotalSM { get; set; }
        public string exkpi { get; set; }
        public string comenexpki { get; set; }
        public Nullable<System.DateTime> MovRe { get; set; }
        public Nullable<int> FolioSolFac { get; set; }
        public string exkpipd { get; set; }
        public string comenexkpipd { get; set; }
        public Nullable<System.DateTime> flingdoc { get; set; }
        public Nullable<int> justifindoc { get; set; }
        public Nullable<System.DateTime> flemifac { get; set; }
        public Nullable<int> justifiemifac { get; set; }
        public string ting { get; set; }
        public Nullable<System.DateTime> fofpoper { get; set; }
        public string uofpoper { get; set; }
        public string usurecep { get; set; }
        public Nullable<System.DateTime> recep { get; set; }
        public string tst { get; set; }
        public string origen { get; set; }
        public Nullable<int> id_encab { get; set; }
        public Nullable<int> TipoDTE { get; set; }
    }
}
