//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_FRMS
    {
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Nom_Boton { get; set; }
        public string Nom_Frm { get; set; }
        public string WebGS { get; set; }
    }
}
