//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_ModNumComp
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string Folio_old { get; set; }
        public string Folio_new { get; set; }
        public Nullable<System.DateTime> momento { get; set; }
    }
}
