//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Pagos
    {
        public Nullable<int> Org { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Monto { get; set; }
        public string MPago { get; set; }
        public Nullable<int> DPago { get; set; }
        public string UsuPag { get; set; }
        public Nullable<System.DateTime> NowSol { get; set; }
        public Nullable<System.DateTime> OkTeso { get; set; }
        public string UsuTeso { get; set; }
        public Nullable<int> Bco { get; set; }
        public Nullable<int> CtaBco { get; set; }
        public Nullable<int> Comp { get; set; }
        public Nullable<System.DateTime> NowComp { get; set; }
        public string GXls { get; set; }
        public string UsuOk1 { get; set; }
        public Nullable<System.DateTime> NowOk1 { get; set; }
        public string UsuOk2 { get; set; }
        public Nullable<System.DateTime> NowOk2 { get; set; }
        public string UsuCenPag { get; set; }
        public Nullable<System.DateTime> Autoclie { get; set; }
        public string Autoclieusu { get; set; }
        public Nullable<System.DateTime> Banco { get; set; }
        public string Bancousu { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public string Cierreusu { get; set; }
    }
}
