//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Pass
    {
        public int ID { get; set; }
        public Nullable<int> Clie { get; set; }
        public Nullable<int> Clasif { get; set; }
        public string Pass { get; set; }
        public string Usu { get; set; }
        public string Orga { get; set; }
    }
}
