//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Restriciones_Bancarias
    {
        public int ID { get; set; }
        public Nullable<int> Clie { get; set; }
        public string NomApo { get; set; }
        public string Rut { get; set; }
        public Nullable<int> MontoRest { get; set; }
        public string Moneda { get; set; }
        public string Obs { get; set; }
        public string Fpago { get; set; }
    }
}
