//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_Saldos_Bancarios
    {
        public int ID { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Cta { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
        public string Usu { get; set; }
    }
}
