//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_TDoc
    {
        public string CodDoc { get; set; }
        public string DesDoc { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Impto { get; set; }
        public string CamA { get; set; }
        public string Decu { get; set; }
        public string SumImp { get; set; }
        public string DSD { get; set; }
        public string DocRes { get; set; }
        public string RotuloDoc { get; set; }
        public string TipoCV { get; set; }
        public string FacElec { get; set; }
        public int id { get; set; }
        public string rotulo_fac_elec { get; set; }
        public Nullable<int> TipoDTE { get; set; }
    }
}
