//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicadores
    {
        public int id { get; set; }
        public Nullable<decimal> UF { get; set; }
        public Nullable<decimal> IVP { get; set; }
        public Nullable<decimal> DOLAR { get; set; }
        public Nullable<decimal> EURO { get; set; }
        public Nullable<decimal> ITCM { get; set; }
        public System.DateTime FECHA { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
