//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfGestionPago
    {
        public int ID { get; set; }
        public string NombreCorto { get; set; }
        public string CPBMes { get; set; }
        public string CPBAño { get; set; }
        public string RotuloDoc { get; set; }
        public Nullable<int> NumDocI { get; set; }
        public string NomAux { get; set; }
        public Nullable<System.DateTime> MovFe { get; set; }
        public Nullable<int> MontoPago { get; set; }
        public Nullable<double> Saldo { get; set; }
        public int NPag { get; set; }
        public int NPOK { get; set; }
        public Nullable<int> NumCent { get; set; }
        public string Archivo { get; set; }
        public Nullable<System.DateTime> PagUrg { get; set; }
        public string ObsSolPago { get; set; }
        public string NomBan { get; set; }
        public string Cta { get; set; }
        public Nullable<int> Rut { get; set; }
        public Nullable<int> Bco { get; set; }
        public Nullable<int> Org { get; set; }
        public string Email { get; set; }
        public string FP { get; set; }
        public string CodAux { get; set; }
        public Nullable<int> Comp { get; set; }
        public Nullable<int> IDCLIE { get; set; }
        public string EmailPag { get; set; }
        public string nom { get; set; }
        public string Obs { get; set; }
        public string Ruta { get; set; }
        public Nullable<System.DateTime> FechaSolPago { get; set; }
        public string UsuSolPago { get; set; }
        public Nullable<System.DateTime> MovFv { get; set; }
        public Nullable<int> estado { get; set; }
        public string Activo { get; set; }
        public string Nombre_Archivo { get; set; }
        public Nullable<int> id_encab { get; set; }
    }
}
