//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_clientes
    {
        public int ID { get; set; }
        public Nullable<int> Rut { get; set; }
        public string Nom { get; set; }
        public string Ruta { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Tipo { get; set; }
        public string EcepCC { get; set; }
        public string IRFS { get; set; }
        public string Activo { get; set; }
        public string Sigla { get; set; }
        public Nullable<double> Tar1 { get; set; }
        public string Mon1 { get; set; }
        public Nullable<double> Tar2 { get; set; }
        public string Mon2 { get; set; }
        public string CC { get; set; }
        public string Holding { get; set; }
        public Nullable<int> BA { get; set; }
        public Nullable<int> ER { get; set; }
        public string Descrip { get; set; }
        public string TES { get; set; }
        public string Expr1 { get; set; }
        public string CtaPag { get; set; }
        public string EmailPag { get; set; }
        public string Mpago { get; set; }
        public string Obs { get; set; }
        public string AdmCheque { get; set; }
        public string RRHH { get; set; }
        public Nullable<int> Grati { get; set; }
        public string ObsGrati { get; set; }
        public Nullable<int> Cola { get; set; }
        public string ObsCola { get; set; }
        public Nullable<int> Mov { get; set; }
        public string ObsMov { get; set; }
        public string formapago { get; set; }
        public Nullable<int> Caja { get; set; }
        public string ObsCaja { get; set; }
        public Nullable<int> Mutual { get; set; }
        public string ObsMutual { get; set; }
        public Nullable<int> DiaSueldo { get; set; }
        public Nullable<int> DiaPago { get; set; }
        public Nullable<int> DiaAnticipo { get; set; }
        public Nullable<int> PagaPSO { get; set; }
        public string ObsRRHH { get; set; }
        public string emailcobro { get; set; }
        public string atencion { get; set; }
        public string TramoPR { get; set; }
        public string IIng { get; set; }
        public string TCheq { get; set; }
        public string rutadestino { get; set; }
        public string CTD { get; set; }
        public string tipomp { get; set; }
        public Nullable<System.DateTime> fechalr { get; set; }
        public string gbo { get; set; }
        public string impsug { get; set; }
        public string senrec { get; set; }
        public string gebo { get; set; }
        public string gess { get; set; }
        public string cart_tes { get; set; }
        public string cart_pay { get; set; }
        public string publicar_eeff { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fsalida { get; set; }
        public string cart_oper { get; set; }
        public string kpif29 { get; set; }
        public string kpieeff { get; set; }
        public string nomfaccl { get; set; }
        public Nullable<bool> kpieeffhabil { get; set; }
        public Nullable<int> numKpif29 { get; set; }
        public Nullable<int> kpif29_automa { get; set; }
    }
}
