//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_usuarios
    {
        public int ID { get; set; }
        public string usuario { get; set; }
        public string Sigla { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> Anexo { get; set; }
        public string Expr2 { get; set; }
        public string nomcorto { get; set; }
        public string nomususoft { get; set; }
        public string pass { get; set; }
        public string jefe { get; set; }
        public string vpeeff { get; set; }
        public string gergen { get; set; }
        public string ger { get; set; }
        public string grupo { get; set; }
        public string appki { get; set; }
        public string superv { get; set; }
    }
}
