//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GSPSOEntities : DbContext
    {
        public GSPSOEntities()
            : base("name=GSPSOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GS_ctrl_cump> GS_ctrl_cump { get; set; }
        public virtual DbSet<Parametros_GS_WEB> Parametros_GS_WEB { get; set; }
        public virtual DbSet<Permisos_GS_WEB> Permisos_GS_WEB { get; set; }
        public virtual DbSet<Biblioteca_GS_Web> Biblioteca_GS_Web { get; set; }
        public virtual DbSet<cab_anticipos> cab_anticipos { get; set; }
        public virtual DbSet<Categoria_Videos> Categoria_Videos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ctrl_acciones> ctrl_acciones { get; set; }
        public virtual DbSet<det_anticipos> det_anticipos { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<files_anticipos> files_anticipos { get; set; }
        public virtual DbSet<GS_AccFrm> GS_AccFrm { get; set; }
        public virtual DbSet<GS_Archivos> GS_Archivos { get; set; }
        public virtual DbSet<GS_Asig_HrrAp> GS_Asig_HrrAp { get; set; }
        public virtual DbSet<GS_Bancos> GS_Bancos { get; set; }
        public virtual DbSet<GS_ClaCtas> GS_ClaCtas { get; set; }
        public virtual DbSet<GS_Clasif_Arch> GS_Clasif_Arch { get; set; }
        public virtual DbSet<GS_Act_Prog> GS_Act_Prog { get; set; }
        public virtual DbSet<GS_Asig_Carg_Clie> GS_Asig_Carg_Clie { get; set; }
        public virtual DbSet<GS_ClasifDoc> GS_ClasifDoc { get; set; }
        public virtual DbSet<GS_Ctas> GS_Ctas { get; set; }
        public virtual DbSet<GS_CtasCtes> GS_CtasCtes { get; set; }
        public virtual DbSet<GS_Detalles> GS_Detalles { get; set; }
        public virtual DbSet<GS_Documentos> GS_Documentos { get; set; }
        public virtual DbSet<GS_HerrApoyo> GS_HerrApoyo { get; set; }
        public virtual DbSet<GS_ModNumComp> GS_ModNumComp { get; set; }
        public virtual DbSet<GS_Pagos> GS_Pagos { get; set; }
        public virtual DbSet<GS_SubClasif_Arch> GS_SubClasif_Arch { get; set; }
        public virtual DbSet<GS_TDoc> GS_TDoc { get; set; }
        public virtual DbSet<indicadores> indicadores { get; set; }
        public virtual DbSet<gs_documentos_new> gs_documentos_new { get; set; }
        public virtual DbSet<GS_FRMS> GS_FRMS { get; set; }
        public virtual DbSet<GS_Medios_Pago> GS_Medios_Pago { get; set; }
        public virtual DbSet<GS_Pass> GS_Pass { get; set; }
        public virtual DbSet<GS_Procesos> GS_Procesos { get; set; }
        public virtual DbSet<GS_Restriciones_Bancarias> GS_Restriciones_Bancarias { get; set; }
        public virtual DbSet<GS_Saldos_Bancarios> GS_Saldos_Bancarios { get; set; }
        public virtual DbSet<GS_SubClasifDoc> GS_SubClasifDoc { get; set; }
        public virtual DbSet<GS_TIPMP> GS_TIPMP { get; set; }
        public virtual DbSet<LogViewsVideos> LogViewsVideos { get; set; }
        public virtual DbSet<Usu> Usu { get; set; }
        public virtual DbSet<VideosTutoriales> VideosTutoriales { get; set; }
        public virtual DbSet<Docs> Docs { get; set; }
        public virtual DbSet<InfGestionPago> InfGestionPago { get; set; }
        public virtual DbSet<l_clientes> l_clientes { get; set; }
        public virtual DbSet<l_usuarios> l_usuarios { get; set; }
        public virtual DbSet<GS_Cargos> GS_Cargos { get; set; }
        public virtual DbSet<parametros> parametros { get; set; }
        public virtual DbSet<Permisos_Softland> Permisos_Softland { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Saldo_Banco> Saldo_Banco { get; set; }
        public virtual DbSet<Tipo_Anticipos> Tipo_Anticipos { get; set; }
        public virtual DbSet<Monedas> Monedas { get; set; }
        public virtual DbSet<TDoc> TDoc { get; set; }
        public virtual DbSet<v_UsuarioIFRS2013> v_UsuarioIFRS2013 { get; set; }
    
        public virtual int PA_insAnticipos(string @base, string anio, string mes, string ttdCod, string ctaDebe, string ctaHaber, string fecha, string monto, string numDocCb, string iD, ObjectParameter return_CpbNum)
        {
            var baseParameter = @base != null ?
                new ObjectParameter("base", @base) :
                new ObjectParameter("base", typeof(string));
    
            var anioParameter = anio != null ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(string));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            var ttdCodParameter = ttdCod != null ?
                new ObjectParameter("TtdCod", ttdCod) :
                new ObjectParameter("TtdCod", typeof(string));
    
            var ctaDebeParameter = ctaDebe != null ?
                new ObjectParameter("CtaDebe", ctaDebe) :
                new ObjectParameter("CtaDebe", typeof(string));
    
            var ctaHaberParameter = ctaHaber != null ?
                new ObjectParameter("CtaHaber", ctaHaber) :
                new ObjectParameter("CtaHaber", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var montoParameter = monto != null ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(string));
    
            var numDocCbParameter = numDocCb != null ?
                new ObjectParameter("NumDocCb", numDocCb) :
                new ObjectParameter("NumDocCb", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insAnticipos", baseParameter, anioParameter, mesParameter, ttdCodParameter, ctaDebeParameter, ctaHaberParameter, fechaParameter, montoParameter, numDocCbParameter, iDParameter, return_CpbNum);
        }
    
        public virtual int PA_AsignacionPermisosAUsuario(string cliente, string usuario, string aux)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var auxParameter = aux != null ?
                new ObjectParameter("Aux", aux) :
                new ObjectParameter("Aux", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_AsignacionPermisosAUsuario", clienteParameter, usuarioParameter, auxParameter);
        }
    
        public virtual int PA_AsignacionPermisosAUsuario1(string cliente, string usuario)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_AsignacionPermisosAUsuario1", clienteParameter, usuarioParameter);
        }
    
        public virtual int PA_AsignacionPermisosAUsuario2(string cliente, string usuario)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_AsignacionPermisosAUsuario2", clienteParameter, usuarioParameter);
        }
    
        public virtual int pa_insercionsoftlandusuarioypermiso(string cliente, string usuario)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insercionsoftlandusuarioypermiso", clienteParameter, usuarioParameter);
        }
    
        public virtual int PA_inspermisosusuario(string cliente, string usuario, ObjectParameter counts)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_inspermisosusuario", clienteParameter, usuarioParameter, counts);
        }
    
        public virtual int PA_consultaselect(string cLIENTE, string uSUARIO)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_consultaselect", cLIENTEParameter, uSUARIOParameter);
        }
    
        public virtual int SP_ExecuteQuery(string cLIENTES, string cONSULTA)
        {
            var cLIENTESParameter = cLIENTES != null ?
                new ObjectParameter("CLIENTES", cLIENTES) :
                new ObjectParameter("CLIENTES", typeof(string));
    
            var cONSULTAParameter = cONSULTA != null ?
                new ObjectParameter("CONSULTA", cONSULTA) :
                new ObjectParameter("CONSULTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ExecuteQuery", cLIENTESParameter, cONSULTAParameter);
        }
    
        public virtual int PA_validaAntesInsertarDinamico(string cliente, string codAux, string nomAux, string rutAux, string email, string usuario)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var codAuxParameter = codAux != null ?
                new ObjectParameter("CodAux", codAux) :
                new ObjectParameter("CodAux", typeof(string));
    
            var nomAuxParameter = nomAux != null ?
                new ObjectParameter("NomAux", nomAux) :
                new ObjectParameter("NomAux", typeof(string));
    
            var rutAuxParameter = rutAux != null ?
                new ObjectParameter("RutAux", rutAux) :
                new ObjectParameter("RutAux", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_validaAntesInsertarDinamico", clienteParameter, codAuxParameter, nomAuxParameter, rutAuxParameter, emailParameter, usuarioParameter);
        }
    
        public virtual int PA_insAnticiposVersion2(string @base, string anio, string mes, string ttdCod, string ctaDebe, string ctaHaber, string fecha, string monto, string numDocCb, string iD, ObjectParameter return_CpbNum)
        {
            var baseParameter = @base != null ?
                new ObjectParameter("base", @base) :
                new ObjectParameter("base", typeof(string));
    
            var anioParameter = anio != null ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(string));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            var ttdCodParameter = ttdCod != null ?
                new ObjectParameter("TtdCod", ttdCod) :
                new ObjectParameter("TtdCod", typeof(string));
    
            var ctaDebeParameter = ctaDebe != null ?
                new ObjectParameter("CtaDebe", ctaDebe) :
                new ObjectParameter("CtaDebe", typeof(string));
    
            var ctaHaberParameter = ctaHaber != null ?
                new ObjectParameter("CtaHaber", ctaHaber) :
                new ObjectParameter("CtaHaber", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var montoParameter = monto != null ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(string));
    
            var numDocCbParameter = numDocCb != null ?
                new ObjectParameter("NumDocCb", numDocCb) :
                new ObjectParameter("NumDocCb", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insAnticiposVersion2", baseParameter, anioParameter, mesParameter, ttdCodParameter, ctaDebeParameter, ctaHaberParameter, fechaParameter, montoParameter, numDocCbParameter, iDParameter, return_CpbNum);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_Valida_Existe_Documento(string cliente, string rut_proveedor, string tipo_Doc, string num_Doc, ObjectParameter counts)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var rut_proveedorParameter = rut_proveedor != null ?
                new ObjectParameter("Rut_proveedor", rut_proveedor) :
                new ObjectParameter("Rut_proveedor", typeof(string));
    
            var tipo_DocParameter = tipo_Doc != null ?
                new ObjectParameter("Tipo_Doc", tipo_Doc) :
                new ObjectParameter("Tipo_Doc", typeof(string));
    
            var num_DocParameter = num_Doc != null ?
                new ObjectParameter("Num_Doc", num_Doc) :
                new ObjectParameter("Num_Doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_Valida_Existe_Documento", clienteParameter, rut_proveedorParameter, tipo_DocParameter, num_DocParameter, counts);
        }
    
        public virtual int sp_selAnticiposProveedor(string id_clie, string cod_aux)
        {
            var id_clieParameter = id_clie != null ?
                new ObjectParameter("id_clie", id_clie) :
                new ObjectParameter("id_clie", typeof(string));
    
            var cod_auxParameter = cod_aux != null ?
                new ObjectParameter("cod_aux", cod_aux) :
                new ObjectParameter("cod_aux", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_selAnticiposProveedor", id_clieParameter, cod_auxParameter);
        }
    
        public virtual int PA_vinculaSoftGs(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_vinculaSoftGs", iDParameter);
        }
    
        public virtual ObjectResult<sp_getClientes_Result> sp_getClientes(string param, Nullable<int> top)
        {
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getClientes_Result>("sp_getClientes", paramParameter, topParameter);
        }
    
        public virtual int pa_insCentralizacionDocumentos(Nullable<int> id_doc)
        {
            var id_docParameter = id_doc.HasValue ?
                new ObjectParameter("id_doc", id_doc) :
                new ObjectParameter("id_doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insCentralizacionDocumentos", id_docParameter);
        }
    
        public virtual ObjectResult<sp_getProveFactu_Result> sp_getProveFactu(string param, Nullable<int> top)
        {
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getProveFactu_Result>("sp_getProveFactu", paramParameter, topParameter);
        }
    }
}
