//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monedas
    {
        public int Id1 { get; set; }
        public Nullable<int> Id { get; set; }
        public string Descrip { get; set; }
        public string Sigla { get; set; }
    }
}
