//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos_GS_WEB
    {
        public int ID { get; set; }
        public int ID_Usu { get; set; }
        public int ID_Parametro { get; set; }
    
        public virtual Parametros_GS_WEB Parametros_GS_WEB { get; set; }
        public virtual Usu Usu { get; set; }
    }
}
