//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldo_Banco
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Corrientes { get; set; }
        public string Corrientes_1 { get; set; }
        public string Corrientes_2 { get; set; }
        public string Corrientes_3 { get; set; }
        public string filename { get; set; }
    }
}
