
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplicationMod
{

using System;
    using System.Collections.Generic;
    
public partial class SolPag
{

    public int ID { get; set; }

    public string NomAux { get; set; }

    public string DesDoc { get; set; }

    public Nullable<int> NumDocI { get; set; }

    public Nullable<int> Total { get; set; }

    public string Ruta { get; set; }

    public Nullable<int> SP { get; set; }

    public Nullable<int> AP { get; set; }

    public string Nombre_Archivo { get; set; }

}

}
