//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Anticipos
    {
        public int id_tanticipo { get; set; }
        public string nom_tanticipo { get; set; }
        public string CtaC { get; set; }
        public string TtdCod { get; set; }
        public Nullable<int> rut_emp { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public string usu_mod { get; set; }
    }
}
