//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UsuarioIFRS2013
    {
        public string Usuario { get; set; }
        public string PassWord { get; set; }
        public string Nombre { get; set; }
        public string Firma { get; set; }
        public int Bloqueado { get; set; }
        public Nullable<System.DateTime> FechaLogin { get; set; }
        public string MotivoBloqueo { get; set; }
        public string Rut { get; set; }
        public string eMail { get; set; }
        public string Sistema { get; set; }
        public string Expr1 { get; set; }
        public string Formulario { get; set; }
        public string Control { get; set; }
    }
}
