
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplicationMod
{

using System;
    using System.Collections.Generic;
    
public partial class Ventas_Fact_Cl
{

    public Nullable<int> ITEM { get; set; }

    public string EMITIDO { get; set; }

    public string DOCUMENTO { get; set; }

    public string FOLIO { get; set; }

    public string FECHA { get; set; }

    public string RUT { get; set; }

    public string CODIGO_CLIENTE { get; set; }

    public string RAZON_SOCIAL { get; set; }

    public string DIRECCIONCLIENTE { get; set; }

    public string SUCURSALCLIENTE { get; set; }

    public Nullable<int> DESCUENTO { get; set; }

    public Nullable<int> RECARGO { get; set; }

    public Nullable<int> EXENTO { get; set; }

    public Nullable<int> NETO { get; set; }

    public Nullable<int> IVA { get; set; }

    public Nullable<int> TASA_IVA { get; set; }

    public Nullable<int> IVA_FUERA_DE_PLAZO { get; set; }

    public Nullable<int> IVA_NO_RETENIDO { get; set; }

    public Nullable<int> IVA_RETENIDO { get; set; }

    public Nullable<int> IMPUESTO { get; set; }

    public Nullable<int> CREDITO_ESPECIAL { get; set; }

    public Nullable<int> CREDITO_ESPECIAL_FUERA_PLAZO { get; set; }

    public Nullable<int> TOTAL { get; set; }

    public string TIPO_DE_MONEDA { get; set; }

    public Nullable<int> TIPO_DE_CAMBIO { get; set; }

    public Nullable<int> TOTAL_OTRA_MONEDA { get; set; }

    public string OBSERVACION { get; set; }

    public string PAGADO { get; set; }

    public string SUCURSAL { get; set; }

    public string ENVIADOLIBRO { get; set; }

    public string ADICIONAL_1 { get; set; }

    public string ADICIONAL_2 { get; set; }

    public string ADICIONAL_3 { get; set; }

    public string ADICIONAL_4 { get; set; }

    public string ADICIONAL_5 { get; set; }

    public string ADICIONAL_6 { get; set; }

    public string CODVENDEDOR { get; set; }

    public string USUARIO { get; set; }

    public string FECHA_DE_CREACION { get; set; }

    public Nullable<int> NRO_DOCUMENTO_ANULADO { get; set; }

    public Nullable<int> TIPO_DOCUMENTO_ANULADO { get; set; }

    public string FECHA_VENCIMIENTO_DOCUMENTO { get; set; }

    public string emp { get; set; }

    public Nullable<int> Cliente { get; set; }

    public int id { get; set; }

    public string proce { get; set; }

    public string tipo_doc { get; set; }

    public string tipodocfacelec { get; set; }

}

}
