//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideosTutoriales
    {
        public int ID_video { get; set; }
        public int id_categoria { get; set; }
        public string ruta_video { get; set; }
        public string ruta_poster { get; set; }
        public string descripcion_video { get; set; }
        public string titulo_video { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Categoria_Videos Categoria_Videos { get; set; }
    }
}
