//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pay_Lenguaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pay_Lenguaje() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.App_GlobalResources.Pay.Lenguaje", typeof(Pay_Lenguaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add request.
        /// </summary>
        public static string agregar_solicitud {
            get {
                return ResourceManager.GetString("agregar_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string año {
            get {
                return ResourceManager.GetString("año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anticipos.
        /// </summary>
        public static string anticipos {
            get {
                return ResourceManager.GetString("anticipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificate of Seniority.
        /// </summary>
        public static string antigüedad {
            get {
                return ResourceManager.GetString("antigüedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        public static string apellidos_form {
            get {
                return ResourceManager.GetString("apellidos_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want approve the registration?.
        /// </summary>
        public static string aprobar_registro {
            get {
                return ResourceManager.GetString("aprobar_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approved.
        /// </summary>
        public static string aprov_reg {
            get {
                return ResourceManager.GetString("aprov_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approve.
        /// </summary>
        public static string aprovar_reg {
            get {
                return ResourceManager.GetString("aprovar_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attached file.
        /// </summary>
        public static string archivo_adjunto {
            get {
                return ResourceManager.GetString("archivo_adjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notices.
        /// </summary>
        public static string avisos {
            get {
                return ResourceManager.GetString("avisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string bienvenido {
            get {
                return ResourceManager.GetString("bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate.
        /// </summary>
        public static string btn_generar {
            get {
                return ResourceManager.GetString("btn_generar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string busqueda_ {
            get {
                return ResourceManager.GetString("busqueda_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Position.
        /// </summary>
        public static string cargo_form {
            get {
                return ResourceManager.GetString("cargo_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        public static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificate of seniority.
        /// </summary>
        public static string certificado_antiguedad {
            get {
                return ResourceManager.GetString("certificado_antiguedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client.
        /// </summary>
        public static string cliente {
            get {
                return ResourceManager.GetString("cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work contract.
        /// </summary>
        public static string contrato_trabajo {
            get {
                return ResourceManager.GetString("contrato_trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Period control.
        /// </summary>
        public static string control_periodos {
            get {
                return ResourceManager.GetString("control_periodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data affiliations.
        /// </summary>
        public static string datos_afiliaciones {
            get {
                return ResourceManager.GetString("datos_afiliaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal information.
        /// </summary>
        public static string datos_personales {
            get {
                return ResourceManager.GetString("datos_personales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you don&apos;t have a Document Viewer plugin for this browser.
        ///            No biggie... you can.
        /// </summary>
        public static string descarga_archivo_1 {
            get {
                return ResourceManager.GetString("descarga_archivo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a click here to download the file..
        /// </summary>
        public static string descarga_archivo_2 {
            get {
                return ResourceManager.GetString("descarga_archivo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrative Day.
        /// </summary>
        public static string dias_adm {
            get {
                return ResourceManager.GetString("dias_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days worked of the month.
        /// </summary>
        public static string dias_trabajados {
            get {
                return ResourceManager.GetString("dias_trabajados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string direccion_form {
            get {
                return ResourceManager.GetString("direccion_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document Name.
        /// </summary>
        public static string docu_index {
            get {
                return ResourceManager.GetString("docu_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string editar_form {
            get {
                return ResourceManager.GetString("editar_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string eliminar_form {
            get {
                return ResourceManager.GetString("eliminar_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want delete the record?.
        /// </summary>
        public static string eliminar_registro {
            get {
                return ResourceManager.GetString("eliminar_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string email_form {
            get {
                return ResourceManager.GetString("email_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee.
        /// </summary>
        public static string empleado {
            get {
                return ResourceManager.GetString("empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is the.
        /// </summary>
        public static string es_el {
            get {
                return ResourceManager.GetString("es_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approval State.
        /// </summary>
        public static string estado_aprobacion {
            get {
                return ResourceManager.GetString("estado_aprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Civil Status.
        /// </summary>
        public static string estadocivil_form {
            get {
                return ResourceManager.GetString("estadocivil_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birthdate.
        /// </summary>
        public static string fecha_nacimiento_form {
            get {
                return ResourceManager.GetString("fecha_nacimiento_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settlement.
        /// </summary>
        public static string finiquito {
            get {
                return ResourceManager.GetString("finiquito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal income form.
        /// </summary>
        public static string formulario_ingresop {
            get {
                return ResourceManager.GetString("formulario_ingresop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Management liquidations.
        /// </summary>
        public static string gestion_liquidaciones {
            get {
                return ResourceManager.GetString("gestion_liquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string guardar_cambios {
            get {
                return ResourceManager.GetString("guardar_cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birthdays of the Month.
        /// </summary>
        public static string home_cumple {
            get {
                return ResourceManager.GetString("home_cumple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add person.
        /// </summary>
        public static string ingresar_persona {
            get {
                return ResourceManager.GetString("ingresar_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free settlements of.
        /// </summary>
        public static string liberar_liquidaciones {
            get {
                return ResourceManager.GetString("liberar_liquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record of the Salary Stub.
        /// </summary>
        public static string liquidaciones_alafecha {
            get {
                return ResourceManager.GetString("liquidaciones_alafecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stubs to date.
        /// </summary>
        public static string liquidaciones_fecha {
            get {
                return ResourceManager.GetString("liquidaciones_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Benefits.
        /// </summary>
        public static string men_beneficios {
            get {
                return ResourceManager.GetString("men_beneficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendar.
        /// </summary>
        public static string men_calendario {
            get {
                return ResourceManager.GetString("men_calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificates.
        /// </summary>
        public static string men_certifi {
            get {
                return ResourceManager.GetString("men_certifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antiquity.
        /// </summary>
        public static string men_certifi_Ant {
            get {
                return ResourceManager.GetString("men_certifi_Ant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Labor Agreement.
        /// </summary>
        public static string men_contrat {
            get {
                return ResourceManager.GetString("men_contrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attachments.
        /// </summary>
        public static string men_contrat_anex {
            get {
                return ResourceManager.GetString("men_contrat_anex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Labor Agreement.
        /// </summary>
        public static string men_contrat_contra {
            get {
                return ResourceManager.GetString("men_contrat_contra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Documents.
        /// </summary>
        public static string men_Documen {
            get {
                return ResourceManager.GetString("men_Documen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settlements.
        /// </summary>
        public static string men_finiquitos {
            get {
                return ResourceManager.GetString("men_finiquitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry.
        /// </summary>
        public static string men_ingresos {
            get {
                return ResourceManager.GetString("men_ingresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salary Stub.
        /// </summary>
        public static string men_liquida {
            get {
                return ResourceManager.GetString("men_liquida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maitenance.
        /// </summary>
        public static string men_mantencion {
            get {
                return ResourceManager.GetString("men_mantencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAIN MENU.
        /// </summary>
        public static string men_Menu_Prin {
            get {
                return ResourceManager.GetString("men_Menu_Prin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Health and Safety.
        /// </summary>
        public static string men_ordyseg {
            get {
                return ResourceManager.GetString("men_ordyseg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company Policies.
        /// </summary>
        public static string men_poli {
            get {
                return ResourceManager.GetString("men_poli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request´s.
        /// </summary>
        public static string men_solicitudes {
            get {
                return ResourceManager.GetString("men_solicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacation claim.
        /// </summary>
        public static string men_solvaca {
            get {
                return ResourceManager.GetString("men_solvaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        public static string mes {
            get {
                return ResourceManager.GetString("mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        public static string monto {
            get {
                return ResourceManager.GetString("monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nationality.
        /// </summary>
        public static string nacionalidad_form {
            get {
                return ResourceManager.GetString("nacionalidad_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string nombre_form {
            get {
                return ResourceManager.GetString("nombre_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string pend_reg {
            get {
                return ResourceManager.GetString("pend_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employees Benefits Policy.
        /// </summary>
        public static string politica_beneficios {
            get {
                return ResourceManager.GetString("politica_beneficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejected.
        /// </summary>
        public static string rechazado {
            get {
                return ResourceManager.GetString("rechazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company Rules.
        /// </summary>
        public static string reg_interno {
            get {
                return ResourceManager.GetString("reg_interno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Number.
        /// </summary>
        public static string rut_form {
            get {
                return ResourceManager.GetString("rut_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Lenguage.
        /// </summary>
        public static string sel_lenguaje {
            get {
                return ResourceManager.GetString("sel_lenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending Request.
        /// </summary>
        public static string sol_pendiente {
            get {
                return ResourceManager.GetString("sol_pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Awaiting requests.
        /// </summary>
        public static string solicitudes_pendientes {
            get {
                return ResourceManager.GetString("solicitudes_pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number.
        /// </summary>
        public static string telefono_form {
            get {
                return ResourceManager.GetString("telefono_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a According to our registration your date of incorporation to the company.
        /// </summary>
        public static string texto_antiguedad {
            get {
                return ResourceManager.GetString("texto_antiguedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mr..
        /// </summary>
        public static string texto_tantiguedad {
            get {
                return ResourceManager.GetString("texto_tantiguedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type request.
        /// </summary>
        public static string tipo_solicitud {
            get {
                return ResourceManager.GetString("tipo_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        public static string vista_prev {
            get {
                return ResourceManager.GetString("vista_prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To view your labor agreement, press the &quot;Generate&quot; button..
        /// </summary>
        public static string visualiza_contrato {
            get {
                return ResourceManager.GetString("visualiza_contrato", resourceCulture);
            }
        }
    }
}
